services:
  oracle-onebox:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-onebox
    environment:
      TZ: ${TZ}
      ORACLE_PWD: ${ORACLE_PWD}
      DB_SERVICE: ${DB_SERVICE}      # FREEPDB1 por defecto
      APEX_ADMIN_PWD: ${APEX_ADMIN_PWD}
      APEX_ADMIN_EMAIL: ${APEX_ADMIN_EMAIL}
      ORDS_PWD: ${ORDS_PWD}
      HTTP_PORT: ${HTTP_PORT}
    ports:
      - "1521:1521"                  # Oracle listener
      - "${HTTP_PORT:-8080}:8080"    # Tomcat/ORDS
    volumes:
      - ./scripts:/opt/oracle/scripts/startup     # hook oficial: ejecuta nuestros scripts al iniciar DB
      - oracle-data:/opt/oracle/oradata           # datos de la DB
      - ords-config:/etc/ords/config              # config persistente de ORDS
    restart: unless-stopped

volumes:
  oracle-data:
  ords-config: