services:
  oracle-onebox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-onebox
    environment:
      TZ: ${TZ}
      ORACLE_PWD: ${ORACLE_PWD}
      DB_SERVICE: ${DB_SERVICE}
      APEX_VERSION: ${APEX_VERSION}
      APEX_ADMIN_PWD: ${APEX_ADMIN_PWD}
      APEX_ADMIN_EMAIL: ${APEX_ADMIN_EMAIL}
      ORDS_PWD: ${ORDS_PWD}
      ORDS_GATEWAY_USER: ${ORDS_GATEWAY_USER}
      CLEAN_ORDS_CONFIG: ${CLEAN_ORDS_CONFIG}
    ports:
      - "1521:1521"           # Oracle Listener
      - "${HTTP_PORT}:8080"   # Tomcat/ORDS
    volumes:
      - oracle-data:/opt/oracle/oradata        # datos de la DB
      - ords-config:/opt/ords/config           # config de ORDS persistente
    restart: unless-stopped

volumes:
  oracle-data:
  ords-config: