version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      apex_prod_net:
        ipv4_address: 172.41.1.10

  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
      args:
        ORACLE_PWD: ${ORACLE_PWD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_SERVICE: ${DB_SERVICE}
        APEX_ADMIN: ${APEX_ADMIN}
        APEX_ADMIN_EMAIL: ${APEX_ADMIN_EMAIL}
        APEX_ADMIN_PWD: ${APEX_ADMIN_PWD}
        ORDS_VERSION: ${ORDS_VERSION}
        APEX_VERSION: ${APEX_VERSION}
        TZ: ${TZ}
    container_name: tomcat-ords
    ports:
      - "8080:8080"
    volumes:
      - ./ords_config:/etc/ords/config
      - ./appfiles:/usr/local/tomcat/webapps/appfiles
      - tomcat_data:/usr/local/tomcat/logs
    depends_on:
      - oracle-db
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - APEX_ADMIN=${APEX_ADMIN}
      - APEX_ADMIN_EMAIL=${APEX_ADMIN_EMAIL}
      - APEX_ADMIN_PWD=${APEX_ADMIN_PWD}
      - TZ=${TZ}
    networks:
      apex_prod_net:
        ipv4_address: 172.41.1.11

volumes:
  oracle_data:
  tomcat_data:

networks:
  apex_prod_net:
    name: apex_prod_net
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.41.0.0/16
          ip_range: 172.41.1.0/24
          gateway: 172.41.1.254