version: "3.9"

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
      TZ: ${TZ}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "echo 'SELECT 1 FROM DUAL;' | /opt/oracle/product/*/dbhome*/bin/sqlplus -s sys/${ORACLE_PWD}@//localhost:1521/${DB_SERVICE} as sysdba || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 180s
    networks:
      - oracle-net

  apex-ords-tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apex-ords-tomcat
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - ords-config:${ORDS_CONFIG}
    restart: unless-stopped
    networks:
      - oracle-net

volumes:
  oracle-data:
  ords-config:

networks:
  oracle-net:
    driver: bridge