version: "3.9"

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=${TZ}
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - apexnet
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'exit' | sqlplus sys/${ORACLE_PWD}@localhost:1521/FREEPDB1 as sysdba"]
      interval: 30s
      timeout: 10s
      retries: 10

  ords-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ords-app
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ords-logs:/home/oracle/logs
    networks:
      - apexnet

volumes:
  oracle-data:
  ords-logs:

networks:
  apexnet:
    driver: bridge